
; This file defines background vehicles for NIS cutscenes.
; If you delete this file, AntagoNISt disables itself.
;
; Each [parameter group] represents a NIS cutscene.
; Group names match NIS names as they appear in VltEd.
;
; Each group must contain exactly 8 valid vehicle names.
; • If a  group doesn't, AntagoNISt uses its vanilla vehicles.
; • If no group does,    AntagoNISt disables itself on launch.
;
; A vehicle name is only valid if
; • there exists a "pvehicle" node of the same name in VltEd, and
; • its VltEd node has a "CLASS" value of either "CAR" or "TRACTOR".



[IntroNisDD]
; Before first prologue race
car1 = copmidsize_nis_ld
car2 = copmidsize_nis_ld
car3 = copmidsize_nis_ld
car4 = trafstwag
car5 = trafficcoup
car6 = traf4dsedc
car7 = trafminivan
car8 = trafpizza



[EndingNis03]
; After Rog's prologue race
car1 = trafamb
car2 = trafstwag
car3 = trafpizza
car4 = trafminivan
car5 = trafficcoup
car6 = traf4dsedc
car7 = trafstwag
car8 = trafpizza



[IntroNisBL15]
; Before Sonny's first race
car1 = copmidsize_nis_ld
car2 = copmidsize_nis_ld
car3 = trafficcoup
car4 = trafpizza
car5 = trafminivan
car6 = trafstwag
car7 = trafsuva
car8 = traftaxi



[IntroNisBL14]
; Before Taz' first race
car1 = copmidsize_nis
car2 = copmidsize_nis_ld
car3 = copmidsize_nis_ld
car4 = trafminivan
car5 = copghost
car6 = trafsuva
car7 = trafstwag
car8 = traftaxi



[IntroNisBL13]
; Before Vic's first race
car1 = copmidsize_nis_ld
car2 = copmidsize_nis_ld
car3 = trafficcoup
car4 = trafpizza
car5 = trafminivan
car6 = trafstwag
car7 = trafsuva
car8 = traftaxi



[IntroNisBL12]
; Before Izzy's first race
car1 = copmidsize_nis
car2 = copmidsize_nis_ld
car3 = copmidsize_nis_ld
car4 = trafminivan
car5 = copghost
car6 = trafsuva
car7 = trafstwag
car8 = traftaxi



[IntroNisBL11]
; Before Big Lou's first race
car1 = eclipsegt
car2 = eclipsegt
car3 = semilog
car4 = trafficcoup
car5 = traf4dsedc
car6 = trafminivan
car7 = copmidsize_nis
car8 = trafstwag



[IntroNisBL10]
; Before Baron's first race
; (only semilog in camera view)
car1 = eclipsegt
car2 = eclipsegt
car3 = semilog
car4 = trafficcoup
car5 = traf4dsedc
car6 = trafminivan
car7 = copmidsize_nis
car8 = trafstwag



[IntroNisBL09]
; Before Earl's first race
car1 = copmidsize_nis_ld
car2 = copmidsize_nis_ld
car3 = trafficcoup
car4 = trafpizza
car5 = trafminivan
car6 = trafstwag
car7 = trafsuva
car8 = traftaxi



; [IntroNisBL08] ; doesn't exist
; Jewels uses IntroNisBL16 instead,
; which has no background vehicles



[IntroNisBL07]
; Before Kaze's first race
car1 = copmidsize_nis_ld
car2 = copmidsize_nis_ld
car3 = copmidsize_nis_ld
car4 = copsuv
car5 = copmidsize_nis_ld
car6 = copsuv
car7 = copmidsize_nis
car8 = semilog



[IntroNisBL06]
; Before Ming's first race
car1 = eclipsegt
car2 = imprezawrx
car3 = trafficcoup
car4 = trafficcoup
car5 = trafpizza
car6 = trafminivan
car7 = semib
car8 = trafpizza



[IntroNisBL05]
; Before Webster's first race
car1 = copmidsize_nis_ld
car2 = copmidsize_nis_ld
car3 = trafficcoup
car4 = trafpizza
car5 = trafminivan
car6 = trafstwag
car7 = trafsuva
car8 = traftaxi



[IntroNisBL04]
; Before JV's first race
; (none in camera view)
car1 = copmidsize_nis_ld
car2 = copmidsize_nis_ld
car3 = trafficcoup
car4 = trafpizza
car5 = trafminivan
car6 = trafstwag
car7 = trafsuva
car8 = traftaxi



[IntroNisBL03]
; Before Ronnie's first race
car1 = copmidsize_nis_ld
car2 = copmidsize_nis_ld
car3 = copmidsize_nis_ld
car4 = copsuv
car5 = copmidsize_nis_ld
car6 = copsuv
car7 = copmidsize_nis
car8 = semilog



[IntroNisBL02]
; Before Bull's first race
; (none in camera view)
car1 = copmidsize_nis_ld
car2 = copmidsize_nis_ld
car3 = copmidsize_nis_ld
car4 = copsuv
car5 = copmidsize_nis_ld
car6 = copsuv
car7 = copmidsize_nis
car8 = semilog



[EndingNis04]
; After final pursuit
car1 = copsportghost
car2 = copsportghost
car3 = copsportghost
car4 = copsportghost
car5 = copsportghost
car6 = copsportghost
car7 = copsportghost
car8 = copcross