
; This file defines background vehicles for NIS cutscenes.
; If you delete this file, AntagoNISt disables itself.
;
; Each [parameter group] represents a NIS cutscene.
; Group names match NIS names as they appear in VltEd.
;
; AntagoNISt ignores groups without exactly 8 valid vehicle names.
; NIS cutscenes of ignored groups use their vanilla background vehicles.
; If no group has exactly 8 valid names, AntagoNISt disables itself.
;
; AntagoNISt considers a vehicle name valid if
; • there exists a "pvehicle" node of the same name in VltEd, and
; • its VltEd node has a "CLASS" value of either "CAR" or "TRACTOR".
;
; Car numbers (car1, car2, etc.) matter for placement in NIS cutscenes.
; Not every NIS cutscene actually uses all its 8 background vehicles.



[IntroNisDD]
; Before first prologue race
car1 = copmidsize_nis_ld
car2 = copmidsize_nis_ld
car3 = copmidsize_nis_ld
car4 = trafstwag
car5 = trafficcoup
car6 = traf4dsedc
car7 = trafminivan
car8 = trafpizza



[EndingNis03]
; After Rog's prologue race
car1 = trafamb
car2 = trafstwag
car3 = trafpizza
car4 = trafminivan
car5 = trafficcoup
car6 = traf4dsedc        ; unused
car7 = trafstwag
car8 = trafpizza



[IntroNisBL15]
; Before Sonny's first race
car1 = copmidsize_nis_ld ; unused
car2 = copmidsize_nis_ld ; unused
car3 = trafficcoup       ; unused
car4 = trafpizza
car5 = trafminivan
car6 = trafstwag
car7 = trafsuva          ; unused
car8 = traftaxi



[IntroNisBL14]
; Before Taz' first race
car1 = copmidsize_nis
car2 = copmidsize_nis_ld
car3 = copmidsize_nis_ld
car4 = trafminivan
car5 = copghost
car6 = trafsuva
car7 = trafstwag
car8 = traftaxi



[IntroNisBL13]
; Before Vic's first race
car1 = copmidsize_nis_ld
car2 = copmidsize_nis_ld
car3 = trafficcoup
car4 = trafpizza
car5 = trafminivan       ; unused
car6 = trafstwag
car7 = trafsuva          ; unused
car8 = traftaxi          ; unused



[IntroNisBL12]
; Before Izzy's first race
car1 = copmidsize_nis    ; unused
car2 = copmidsize_nis_ld
car3 = copmidsize_nis_ld ; unused
car4 = trafminivan
car5 = copghost
car6 = trafsuva
car7 = trafstwag         ; unused
car8 = traftaxi          ; unused



[IntroNisBL11]
; Before Big Lou's first race
car1 = eclipsegt
car2 = eclipsegt
car3 = semilog           ; unused
car4 = trafficcoup
car5 = traf4dsedc
car6 = trafminivan       ; unused
car7 = copmidsize_nis    ; unused
car8 = trafstwag         ; unused



[IntroNisBL10]
; Before Baron's first race
car1 = eclipsegt         ; unused
car2 = eclipsegt         ; unused
car3 = semilog
car4 = trafficcoup       ; unused
car5 = traf4dsedc        ; unused
car6 = trafminivan       ; unused
car7 = copmidsize_nis    ; unused
car8 = trafstwag         ; unused



[IntroNisBL09]
; Before Earl's first race
car1 = copmidsize_nis_ld ; unused
car2 = copmidsize_nis_ld ; unused
car3 = trafficcoup
car4 = trafpizza         ; unused
car5 = trafminivan       ; unused
car6 = trafstwag
car7 = trafsuva          ; unused
car8 = traftaxi          ; unused



; [IntroNisBL08] ; doesn't exist
; Jewels uses IntroNisBL16 instead,
; which has no background vehicles



[IntroNisBL07]
; Before Kaze's first race
car1 = copmidsize_nis_ld
car2 = copmidsize_nis_ld
car3 = copmidsize_nis_ld
car4 = copsuv
car5 = copmidsize_nis_ld
car6 = copsuv
car7 = copmidsize_nis    ; unused
car8 = semilog



[IntroNisBL06]
; Before Ming's first race
car1 = eclipsegt
car2 = imprezawrx
car3 = trafficcoup
car4 = trafficcoup
car5 = trafpizza
car6 = trafminivan
car7 = semib             ; unused
car8 = trafpizza         ; unused



[IntroNisBL05]
; Before Webster's first race
car1 = copmidsize_nis_ld ; unused
car2 = copmidsize_nis_ld
car3 = trafficcoup
car4 = trafpizza
car5 = trafminivan
car6 = trafstwag
car7 = trafsuva
car8 = traftaxi          ; unused



[IntroNisBL04]
; Before JV's first race
car1 = copmidsize_nis_ld ; unused
car2 = copmidsize_nis_ld ; unused
car3 = trafficcoup       ; unused
car4 = trafpizza         ; unused
car5 = trafminivan       ; unused
car6 = trafstwag         ; unused
car7 = trafsuva          ; unused
car8 = traftaxi          ; unused



[IntroNisBL03]
; Before Ronnie's first race
car1 = copmidsize_nis_ld
car2 = copmidsize_nis_ld ; unused
car3 = copmidsize_nis_ld ; unused
car4 = copsuv            ; unused
car5 = copmidsize_nis_ld ; unused
car6 = copsuv            ; unused
car7 = copmidsize_nis    ; unused
car8 = semilog           ; unused



[IntroNisBL02]
; Before Bull's first race
car1 = copmidsize_nis_ld ; unused
car2 = copmidsize_nis_ld ; unused
car3 = copmidsize_nis_ld ; unused
car4 = copsuv            ; unused
car5 = copmidsize_nis_ld ; unused
car6 = copsuv            ; unused
car7 = copmidsize_nis    ; unused
car8 = semilog           ; unused



[EndingNis04]
; After final pursuit
car1 = copsportghost
car2 = copsportghost
car3 = copsportghost
car4 = copsportghost
car5 = copsportghost
car6 = copsportghost
car7 = copsportghost
car8 = copcross